management:
  endpoints:
    web:
      exposure:
        include: "*"
spring.jpa.hibernate.naming:
  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#server.servlet.context-parameters.package: com.sap.grc.ctrl
#server.servlet.context-parameters.DBConnection: com.sap.cloud.servicesdk.spring.SpringConnectionProvider
#server.servlet.context-parameters.ExtensionConfig: com.sap.cloud.servicesdk.spring.SpringExtensionConfig
---
spring:
  profiles: default
  datasource:
    url: jdbc:sap://localhost:30015/?currentschema=C5C261A595B84CF9B5C6EDC5EE5632A6
    username: SBSS_99576839431497164421027533288227080982870328481689947431732643534
    password: Uv2.M6T3-pb5OfHCQPj7TZD6RP33syLwxTrU3ZzkZwyzEUzaF.roct.eVf.V6vlZGUCruOMlD49CgzS7ZtDky3HvgMznyqIZVAi5Dd2DmUp5GFfDvXsHEeTZSbuyQK5I
    driverClassName: com.sap.db.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource